/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface CompetitionRef {
  id: number;
  name: string;
  code: string;
}

export interface TeamRef {
  id: number;
  name: string;
  shortName: string;
  tla: string;
}

export interface ScoreDetail {
  /** @nullable */
  home?: number | null;
  /** @nullable */
  away?: number | null;
}

export interface Score {
  /** @nullable */
  winner?: string | null;
  duration?: string;
  fullTime: ScoreDetail;
  halfTime: ScoreDetail;
}

export interface Match {
  id: number;
  utcDate: string;
  status: string;
  /** @nullable */
  matchday?: number | null;
  stage?: string;
  /** @nullable */
  minute?: number | null;
  /** @nullable */
  injuryTime?: number | null;
  competition: CompetitionRef;
  homeTeam: TeamRef;
  awayTeam: TeamRef;
  score: Score;
}

export interface Standing {
  position: number;
  team: TeamRef;
  playedGames: number;
  won: number;
  draw: number;
  lost: number;
  points: number;
  goalsFor: number;
  goalsAgainst: number;
  goalDifference: number;
}

export type ScorerPlayer = {
  name: string;
  nationality: string;
};

export type ScorerTeam = {
  name: string;
};

export interface Scorer {
  player: ScorerPlayer;
  team: ScorerTeam;
  goals: number;
  /** @nullable */
  assists?: number | null;
  /** @nullable */
  penalties?: number | null;
}

export interface NewsArticle {
  title: string;
  link: string;
  description: string;
  pubDate: string;
}

export interface SquadMember {
  id: number;
  name: string;
  /** @nullable */
  position?: string | null;
  nationality?: string;
}

export interface TeamDetail {
  id: number;
  name: string;
  shortName: string;
  tla: string;
  crest: string;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  founded?: number | null;
  /** @nullable */
  clubColors?: string | null;
  /** @nullable */
  venue?: string | null;
  runningCompetitions?: CompetitionRef[];
  squad?: SquadMember[];
}

export interface GoalEvent {
  minute: number;
  /** @nullable */
  injuryTime?: number | null;
  team: string;
  scorer: string;
  /** @nullable */
  assist?: string | null;
  type?: string;
}

export type MatchDetailRefereesItem = {
  name?: string;
  /** @nullable */
  nationality?: string | null;
};

export interface MatchDetail {
  id: number;
  utcDate: string;
  status: string;
  /** @nullable */
  matchday?: number | null;
  stage?: string;
  /** @nullable */
  minute?: number | null;
  /** @nullable */
  injuryTime?: number | null;
  competition: CompetitionRef;
  homeTeam: TeamRef;
  awayTeam: TeamRef;
  score: Score;
  goals?: GoalEvent[];
  referees?: MatchDetailRefereesItem[];
}

export type H2HResultAggregatesHomeTeam = {
  id?: number;
  name?: string;
  wins?: number;
  draws?: number;
  losses?: number;
};

export type H2HResultAggregatesAwayTeam = {
  id?: number;
  name?: string;
  wins?: number;
  draws?: number;
  losses?: number;
};

export type H2HResultAggregates = {
  numberOfMatches?: number;
  totalGoals?: number;
  homeTeam?: H2HResultAggregatesHomeTeam;
  awayTeam?: H2HResultAggregatesAwayTeam;
};

export interface H2HResult {
  aggregates: H2HResultAggregates;
  matches: Match[];
}

export type GetScoresParams = {
/**
 * Date in YYYY-MM-DD format (defaults to today)
 */
date?: string;
};

export type GetStandingsParams = {
/**
 * League code (e.g. PL, BL1, PD)
 */
league: string;
};

export type GetTopScorersParams = {
league: string;
limit?: number;
};

export type GetTeamParams = {
name: string;
};

export type GetFixturesParams = {
teamId: number;
};

export type GetMatchH2HParams = {
limit?: number;
};

