/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Get live matches
 */
export const GetLiveMatchesResponseItem = zod.object({
  "id": zod.number(),
  "utcDate": zod.string(),
  "status": zod.string(),
  "matchday": zod.number().nullish(),
  "stage": zod.string().optional(),
  "minute": zod.number().nullish(),
  "injuryTime": zod.number().nullish(),
  "competition": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "code": zod.string()
}),
  "homeTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "awayTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "score": zod.object({
  "winner": zod.string().nullish(),
  "duration": zod.string().optional(),
  "fullTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
}),
  "halfTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
})
})
})
export const GetLiveMatchesResponse = zod.array(GetLiveMatchesResponseItem)


/**
 * @summary Get scores for a date
 */
export const GetScoresQueryParams = zod.object({
  "date": zod.coerce.string().optional().describe('Date in YYYY-MM-DD format (defaults to today)')
})

export const GetScoresResponseItem = zod.object({
  "id": zod.number(),
  "utcDate": zod.string(),
  "status": zod.string(),
  "matchday": zod.number().nullish(),
  "stage": zod.string().optional(),
  "minute": zod.number().nullish(),
  "injuryTime": zod.number().nullish(),
  "competition": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "code": zod.string()
}),
  "homeTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "awayTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "score": zod.object({
  "winner": zod.string().nullish(),
  "duration": zod.string().optional(),
  "fullTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
}),
  "halfTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
})
})
})
export const GetScoresResponse = zod.array(GetScoresResponseItem)


/**
 * @summary Get league standings
 */
export const GetStandingsQueryParams = zod.object({
  "league": zod.coerce.string().describe('League code (e.g. PL, BL1, PD)')
})

export const GetStandingsResponseItem = zod.object({
  "position": zod.number(),
  "team": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "playedGames": zod.number(),
  "won": zod.number(),
  "draw": zod.number(),
  "lost": zod.number(),
  "points": zod.number(),
  "goalsFor": zod.number(),
  "goalsAgainst": zod.number(),
  "goalDifference": zod.number()
})
export const GetStandingsResponse = zod.array(GetStandingsResponseItem)


/**
 * @summary Get top scorers for a league
 */
export const GetTopScorersQueryParams = zod.object({
  "league": zod.coerce.string(),
  "limit": zod.coerce.number().optional()
})

export const GetTopScorersResponseItem = zod.object({
  "player": zod.object({
  "name": zod.string(),
  "nationality": zod.string()
}),
  "team": zod.object({
  "name": zod.string()
}),
  "goals": zod.number(),
  "assists": zod.number().nullish(),
  "penalties": zod.number().nullish()
})
export const GetTopScorersResponse = zod.array(GetTopScorersResponseItem)


/**
 * @summary Get latest football news
 */
export const GetNewsResponseItem = zod.object({
  "title": zod.string(),
  "link": zod.string(),
  "description": zod.string(),
  "pubDate": zod.string()
})
export const GetNewsResponse = zod.array(GetNewsResponseItem)


/**
 * @summary Search for a team
 */
export const GetTeamQueryParams = zod.object({
  "name": zod.coerce.string()
})

export const GetTeamResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string(),
  "crest": zod.string(),
  "website": zod.string().nullish(),
  "founded": zod.number().nullish(),
  "clubColors": zod.string().nullish(),
  "venue": zod.string().nullish(),
  "runningCompetitions": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "code": zod.string()
})).optional(),
  "squad": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "position": zod.string().nullish(),
  "nationality": zod.string().optional()
})).optional()
})


/**
 * @summary Get upcoming fixtures for a team
 */
export const GetFixturesQueryParams = zod.object({
  "teamId": zod.coerce.number()
})

export const GetFixturesResponseItem = zod.object({
  "id": zod.number(),
  "utcDate": zod.string(),
  "status": zod.string(),
  "matchday": zod.number().nullish(),
  "stage": zod.string().optional(),
  "minute": zod.number().nullish(),
  "injuryTime": zod.number().nullish(),
  "competition": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "code": zod.string()
}),
  "homeTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "awayTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "score": zod.object({
  "winner": zod.string().nullish(),
  "duration": zod.string().optional(),
  "fullTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
}),
  "halfTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
})
})
})
export const GetFixturesResponse = zod.array(GetFixturesResponseItem)


/**
 * @summary Get full match details
 */
export const GetMatchParams = zod.object({
  "id": zod.coerce.number()
})

export const GetMatchResponse = zod.object({
  "id": zod.number(),
  "utcDate": zod.string(),
  "status": zod.string(),
  "matchday": zod.number().nullish(),
  "stage": zod.string().optional(),
  "minute": zod.number().nullish(),
  "injuryTime": zod.number().nullish(),
  "competition": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "code": zod.string()
}),
  "homeTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "awayTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "score": zod.object({
  "winner": zod.string().nullish(),
  "duration": zod.string().optional(),
  "fullTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
}),
  "halfTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
})
}),
  "goals": zod.array(zod.object({
  "minute": zod.number(),
  "injuryTime": zod.number().nullish(),
  "team": zod.string(),
  "scorer": zod.string(),
  "assist": zod.string().nullish(),
  "type": zod.string().optional()
})).optional(),
  "referees": zod.array(zod.object({
  "name": zod.string().optional(),
  "nationality": zod.string().nullish()
})).optional()
})


/**
 * @summary Get head-to-head stats for a match
 */
export const GetMatchH2HParams = zod.object({
  "id": zod.coerce.number()
})

export const GetMatchH2HQueryParams = zod.object({
  "limit": zod.coerce.number().optional()
})

export const GetMatchH2HResponse = zod.object({
  "aggregates": zod.object({
  "numberOfMatches": zod.number().optional(),
  "totalGoals": zod.number().optional(),
  "homeTeam": zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "wins": zod.number().optional(),
  "draws": zod.number().optional(),
  "losses": zod.number().optional()
}).optional(),
  "awayTeam": zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "wins": zod.number().optional(),
  "draws": zod.number().optional(),
  "losses": zod.number().optional()
}).optional()
}),
  "matches": zod.array(zod.object({
  "id": zod.number(),
  "utcDate": zod.string(),
  "status": zod.string(),
  "matchday": zod.number().nullish(),
  "stage": zod.string().optional(),
  "minute": zod.number().nullish(),
  "injuryTime": zod.number().nullish(),
  "competition": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "code": zod.string()
}),
  "homeTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "awayTeam": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "shortName": zod.string(),
  "tla": zod.string()
}),
  "score": zod.object({
  "winner": zod.string().nullish(),
  "duration": zod.string().optional(),
  "fullTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
}),
  "halfTime": zod.object({
  "home": zod.number().nullish(),
  "away": zod.number().nullish()
})
})
}))
})


