/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Get live matches
 */
export declare const GetLiveMatchesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    utcDate: zod.ZodString;
    status: zod.ZodString;
    matchday: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    stage: zod.ZodOptional<zod.ZodString>;
    minute: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    injuryTime: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    competition: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        code: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        code: string;
        id: number;
        name: string;
    }, {
        code: string;
        id: number;
        name: string;
    }>;
    homeTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    awayTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    score: zod.ZodObject<{
        winner: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodString>;
        fullTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
        halfTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}>;
export declare const GetLiveMatchesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    utcDate: zod.ZodString;
    status: zod.ZodString;
    matchday: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    stage: zod.ZodOptional<zod.ZodString>;
    minute: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    injuryTime: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    competition: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        code: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        code: string;
        id: number;
        name: string;
    }, {
        code: string;
        id: number;
        name: string;
    }>;
    homeTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    awayTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    score: zod.ZodObject<{
        winner: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodString>;
        fullTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
        halfTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}>, "many">;
/**
 * @summary Get scores for a date
 */
export declare const GetScoresQueryParams: zod.ZodObject<{
    date: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    date?: string | undefined;
}, {
    date?: string | undefined;
}>;
export declare const GetScoresResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    utcDate: zod.ZodString;
    status: zod.ZodString;
    matchday: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    stage: zod.ZodOptional<zod.ZodString>;
    minute: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    injuryTime: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    competition: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        code: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        code: string;
        id: number;
        name: string;
    }, {
        code: string;
        id: number;
        name: string;
    }>;
    homeTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    awayTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    score: zod.ZodObject<{
        winner: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodString>;
        fullTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
        halfTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}>;
export declare const GetScoresResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    utcDate: zod.ZodString;
    status: zod.ZodString;
    matchday: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    stage: zod.ZodOptional<zod.ZodString>;
    minute: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    injuryTime: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    competition: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        code: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        code: string;
        id: number;
        name: string;
    }, {
        code: string;
        id: number;
        name: string;
    }>;
    homeTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    awayTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    score: zod.ZodObject<{
        winner: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodString>;
        fullTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
        halfTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}>, "many">;
/**
 * @summary Get league standings
 */
export declare const GetStandingsQueryParams: zod.ZodObject<{
    league: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    league: string;
}, {
    league: string;
}>;
export declare const GetStandingsResponseItem: zod.ZodObject<{
    position: zod.ZodNumber;
    team: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    playedGames: zod.ZodNumber;
    won: zod.ZodNumber;
    draw: zod.ZodNumber;
    lost: zod.ZodNumber;
    points: zod.ZodNumber;
    goalsFor: zod.ZodNumber;
    goalsAgainst: zod.ZodNumber;
    goalDifference: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    position: number;
    team: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    playedGames: number;
    won: number;
    draw: number;
    lost: number;
    points: number;
    goalsFor: number;
    goalsAgainst: number;
    goalDifference: number;
}, {
    position: number;
    team: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    playedGames: number;
    won: number;
    draw: number;
    lost: number;
    points: number;
    goalsFor: number;
    goalsAgainst: number;
    goalDifference: number;
}>;
export declare const GetStandingsResponse: zod.ZodArray<zod.ZodObject<{
    position: zod.ZodNumber;
    team: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    playedGames: zod.ZodNumber;
    won: zod.ZodNumber;
    draw: zod.ZodNumber;
    lost: zod.ZodNumber;
    points: zod.ZodNumber;
    goalsFor: zod.ZodNumber;
    goalsAgainst: zod.ZodNumber;
    goalDifference: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    position: number;
    team: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    playedGames: number;
    won: number;
    draw: number;
    lost: number;
    points: number;
    goalsFor: number;
    goalsAgainst: number;
    goalDifference: number;
}, {
    position: number;
    team: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    playedGames: number;
    won: number;
    draw: number;
    lost: number;
    points: number;
    goalsFor: number;
    goalsAgainst: number;
    goalDifference: number;
}>, "many">;
/**
 * @summary Get top scorers for a league
 */
export declare const GetTopScorersQueryParams: zod.ZodObject<{
    league: zod.ZodString;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    league: string;
    limit?: number | undefined;
}, {
    league: string;
    limit?: number | undefined;
}>;
export declare const GetTopScorersResponseItem: zod.ZodObject<{
    player: zod.ZodObject<{
        name: zod.ZodString;
        nationality: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        name: string;
        nationality: string;
    }, {
        name: string;
        nationality: string;
    }>;
    team: zod.ZodObject<{
        name: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        name: string;
    }, {
        name: string;
    }>;
    goals: zod.ZodNumber;
    assists: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    penalties: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
}, "strip", zod.ZodTypeAny, {
    team: {
        name: string;
    };
    player: {
        name: string;
        nationality: string;
    };
    goals: number;
    assists?: number | null | undefined;
    penalties?: number | null | undefined;
}, {
    team: {
        name: string;
    };
    player: {
        name: string;
        nationality: string;
    };
    goals: number;
    assists?: number | null | undefined;
    penalties?: number | null | undefined;
}>;
export declare const GetTopScorersResponse: zod.ZodArray<zod.ZodObject<{
    player: zod.ZodObject<{
        name: zod.ZodString;
        nationality: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        name: string;
        nationality: string;
    }, {
        name: string;
        nationality: string;
    }>;
    team: zod.ZodObject<{
        name: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        name: string;
    }, {
        name: string;
    }>;
    goals: zod.ZodNumber;
    assists: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    penalties: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
}, "strip", zod.ZodTypeAny, {
    team: {
        name: string;
    };
    player: {
        name: string;
        nationality: string;
    };
    goals: number;
    assists?: number | null | undefined;
    penalties?: number | null | undefined;
}, {
    team: {
        name: string;
    };
    player: {
        name: string;
        nationality: string;
    };
    goals: number;
    assists?: number | null | undefined;
    penalties?: number | null | undefined;
}>, "many">;
/**
 * @summary Get latest football news
 */
export declare const GetNewsResponseItem: zod.ZodObject<{
    title: zod.ZodString;
    link: zod.ZodString;
    description: zod.ZodString;
    pubDate: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    title: string;
    link: string;
    description: string;
    pubDate: string;
}, {
    title: string;
    link: string;
    description: string;
    pubDate: string;
}>;
export declare const GetNewsResponse: zod.ZodArray<zod.ZodObject<{
    title: zod.ZodString;
    link: zod.ZodString;
    description: zod.ZodString;
    pubDate: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    title: string;
    link: string;
    description: string;
    pubDate: string;
}, {
    title: string;
    link: string;
    description: string;
    pubDate: string;
}>, "many">;
/**
 * @summary Search for a team
 */
export declare const GetTeamQueryParams: zod.ZodObject<{
    name: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
}, {
    name: string;
}>;
export declare const GetTeamResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    shortName: zod.ZodString;
    tla: zod.ZodString;
    crest: zod.ZodString;
    website: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    founded: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    clubColors: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    venue: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    runningCompetitions: zod.ZodOptional<zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        code: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        code: string;
        id: number;
        name: string;
    }, {
        code: string;
        id: number;
        name: string;
    }>, "many">>;
    squad: zod.ZodOptional<zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        position: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        nationality: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        position?: string | null | undefined;
        nationality?: string | undefined;
    }, {
        id: number;
        name: string;
        position?: string | null | undefined;
        nationality?: string | undefined;
    }>, "many">>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    shortName: string;
    tla: string;
    crest: string;
    website?: string | null | undefined;
    founded?: number | null | undefined;
    clubColors?: string | null | undefined;
    venue?: string | null | undefined;
    runningCompetitions?: {
        code: string;
        id: number;
        name: string;
    }[] | undefined;
    squad?: {
        id: number;
        name: string;
        position?: string | null | undefined;
        nationality?: string | undefined;
    }[] | undefined;
}, {
    id: number;
    name: string;
    shortName: string;
    tla: string;
    crest: string;
    website?: string | null | undefined;
    founded?: number | null | undefined;
    clubColors?: string | null | undefined;
    venue?: string | null | undefined;
    runningCompetitions?: {
        code: string;
        id: number;
        name: string;
    }[] | undefined;
    squad?: {
        id: number;
        name: string;
        position?: string | null | undefined;
        nationality?: string | undefined;
    }[] | undefined;
}>;
/**
 * @summary Get upcoming fixtures for a team
 */
export declare const GetFixturesQueryParams: zod.ZodObject<{
    teamId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    teamId: number;
}, {
    teamId: number;
}>;
export declare const GetFixturesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    utcDate: zod.ZodString;
    status: zod.ZodString;
    matchday: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    stage: zod.ZodOptional<zod.ZodString>;
    minute: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    injuryTime: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    competition: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        code: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        code: string;
        id: number;
        name: string;
    }, {
        code: string;
        id: number;
        name: string;
    }>;
    homeTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    awayTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    score: zod.ZodObject<{
        winner: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodString>;
        fullTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
        halfTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}>;
export declare const GetFixturesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    utcDate: zod.ZodString;
    status: zod.ZodString;
    matchday: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    stage: zod.ZodOptional<zod.ZodString>;
    minute: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    injuryTime: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    competition: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        code: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        code: string;
        id: number;
        name: string;
    }, {
        code: string;
        id: number;
        name: string;
    }>;
    homeTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    awayTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    score: zod.ZodObject<{
        winner: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodString>;
        fullTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
        halfTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
}>, "many">;
/**
 * @summary Get full match details
 */
export declare const GetMatchParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetMatchResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    utcDate: zod.ZodString;
    status: zod.ZodString;
    matchday: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    stage: zod.ZodOptional<zod.ZodString>;
    minute: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    injuryTime: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    competition: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        code: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        code: string;
        id: number;
        name: string;
    }, {
        code: string;
        id: number;
        name: string;
    }>;
    homeTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    awayTeam: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        shortName: zod.ZodString;
        tla: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }, {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    }>;
    score: zod.ZodObject<{
        winner: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        duration: zod.ZodOptional<zod.ZodString>;
        fullTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
        halfTime: zod.ZodObject<{
            home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        }, "strip", zod.ZodTypeAny, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }, {
            home?: number | null | undefined;
            away?: number | null | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }, {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    }>;
    goals: zod.ZodOptional<zod.ZodArray<zod.ZodObject<{
        minute: zod.ZodNumber;
        injuryTime: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        team: zod.ZodString;
        scorer: zod.ZodString;
        assist: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        type: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        minute: number;
        team: string;
        scorer: string;
        type?: string | undefined;
        injuryTime?: number | null | undefined;
        assist?: string | null | undefined;
    }, {
        minute: number;
        team: string;
        scorer: string;
        type?: string | undefined;
        injuryTime?: number | null | undefined;
        assist?: string | null | undefined;
    }>, "many">>;
    referees: zod.ZodOptional<zod.ZodArray<zod.ZodObject<{
        name: zod.ZodOptional<zod.ZodString>;
        nationality: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        name?: string | undefined;
        nationality?: string | null | undefined;
    }, {
        name?: string | undefined;
        nationality?: string | null | undefined;
    }>, "many">>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
    goals?: {
        minute: number;
        team: string;
        scorer: string;
        type?: string | undefined;
        injuryTime?: number | null | undefined;
        assist?: string | null | undefined;
    }[] | undefined;
    referees?: {
        name?: string | undefined;
        nationality?: string | null | undefined;
    }[] | undefined;
}, {
    status: string;
    id: number;
    utcDate: string;
    competition: {
        code: string;
        id: number;
        name: string;
    };
    homeTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    awayTeam: {
        id: number;
        name: string;
        shortName: string;
        tla: string;
    };
    score: {
        fullTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        halfTime: {
            home?: number | null | undefined;
            away?: number | null | undefined;
        };
        winner?: string | null | undefined;
        duration?: string | undefined;
    };
    matchday?: number | null | undefined;
    stage?: string | undefined;
    minute?: number | null | undefined;
    injuryTime?: number | null | undefined;
    goals?: {
        minute: number;
        team: string;
        scorer: string;
        type?: string | undefined;
        injuryTime?: number | null | undefined;
        assist?: string | null | undefined;
    }[] | undefined;
    referees?: {
        name?: string | undefined;
        nationality?: string | null | undefined;
    }[] | undefined;
}>;
/**
 * @summary Get head-to-head stats for a match
 */
export declare const GetMatchH2HParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetMatchH2HQueryParams: zod.ZodObject<{
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    limit?: number | undefined;
}, {
    limit?: number | undefined;
}>;
export declare const GetMatchH2HResponse: zod.ZodObject<{
    aggregates: zod.ZodObject<{
        numberOfMatches: zod.ZodOptional<zod.ZodNumber>;
        totalGoals: zod.ZodOptional<zod.ZodNumber>;
        homeTeam: zod.ZodOptional<zod.ZodObject<{
            id: zod.ZodOptional<zod.ZodNumber>;
            name: zod.ZodOptional<zod.ZodString>;
            wins: zod.ZodOptional<zod.ZodNumber>;
            draws: zod.ZodOptional<zod.ZodNumber>;
            losses: zod.ZodOptional<zod.ZodNumber>;
        }, "strip", zod.ZodTypeAny, {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        }, {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        }>>;
        awayTeam: zod.ZodOptional<zod.ZodObject<{
            id: zod.ZodOptional<zod.ZodNumber>;
            name: zod.ZodOptional<zod.ZodString>;
            wins: zod.ZodOptional<zod.ZodNumber>;
            draws: zod.ZodOptional<zod.ZodNumber>;
            losses: zod.ZodOptional<zod.ZodNumber>;
        }, "strip", zod.ZodTypeAny, {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        }, {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        }>>;
    }, "strip", zod.ZodTypeAny, {
        homeTeam?: {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        } | undefined;
        awayTeam?: {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        } | undefined;
        numberOfMatches?: number | undefined;
        totalGoals?: number | undefined;
    }, {
        homeTeam?: {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        } | undefined;
        awayTeam?: {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        } | undefined;
        numberOfMatches?: number | undefined;
        totalGoals?: number | undefined;
    }>;
    matches: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        utcDate: zod.ZodString;
        status: zod.ZodString;
        matchday: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        stage: zod.ZodOptional<zod.ZodString>;
        minute: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        injuryTime: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        competition: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            code: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            code: string;
            id: number;
            name: string;
        }, {
            code: string;
            id: number;
            name: string;
        }>;
        homeTeam: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            shortName: zod.ZodString;
            tla: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        }, {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        }>;
        awayTeam: zod.ZodObject<{
            id: zod.ZodNumber;
            name: zod.ZodString;
            shortName: zod.ZodString;
            tla: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        }, {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        }>;
        score: zod.ZodObject<{
            winner: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            duration: zod.ZodOptional<zod.ZodString>;
            fullTime: zod.ZodObject<{
                home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
                away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            }, "strip", zod.ZodTypeAny, {
                home?: number | null | undefined;
                away?: number | null | undefined;
            }, {
                home?: number | null | undefined;
                away?: number | null | undefined;
            }>;
            halfTime: zod.ZodObject<{
                home: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
                away: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
            }, "strip", zod.ZodTypeAny, {
                home?: number | null | undefined;
                away?: number | null | undefined;
            }, {
                home?: number | null | undefined;
                away?: number | null | undefined;
            }>;
        }, "strip", zod.ZodTypeAny, {
            fullTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            halfTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            winner?: string | null | undefined;
            duration?: string | undefined;
        }, {
            fullTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            halfTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            winner?: string | null | undefined;
            duration?: string | undefined;
        }>;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: number;
        utcDate: string;
        competition: {
            code: string;
            id: number;
            name: string;
        };
        homeTeam: {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        };
        awayTeam: {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        };
        score: {
            fullTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            halfTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            winner?: string | null | undefined;
            duration?: string | undefined;
        };
        matchday?: number | null | undefined;
        stage?: string | undefined;
        minute?: number | null | undefined;
        injuryTime?: number | null | undefined;
    }, {
        status: string;
        id: number;
        utcDate: string;
        competition: {
            code: string;
            id: number;
            name: string;
        };
        homeTeam: {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        };
        awayTeam: {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        };
        score: {
            fullTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            halfTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            winner?: string | null | undefined;
            duration?: string | undefined;
        };
        matchday?: number | null | undefined;
        stage?: string | undefined;
        minute?: number | null | undefined;
        injuryTime?: number | null | undefined;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    aggregates: {
        homeTeam?: {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        } | undefined;
        awayTeam?: {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        } | undefined;
        numberOfMatches?: number | undefined;
        totalGoals?: number | undefined;
    };
    matches: {
        status: string;
        id: number;
        utcDate: string;
        competition: {
            code: string;
            id: number;
            name: string;
        };
        homeTeam: {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        };
        awayTeam: {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        };
        score: {
            fullTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            halfTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            winner?: string | null | undefined;
            duration?: string | undefined;
        };
        matchday?: number | null | undefined;
        stage?: string | undefined;
        minute?: number | null | undefined;
        injuryTime?: number | null | undefined;
    }[];
}, {
    aggregates: {
        homeTeam?: {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        } | undefined;
        awayTeam?: {
            id?: number | undefined;
            name?: string | undefined;
            wins?: number | undefined;
            draws?: number | undefined;
            losses?: number | undefined;
        } | undefined;
        numberOfMatches?: number | undefined;
        totalGoals?: number | undefined;
    };
    matches: {
        status: string;
        id: number;
        utcDate: string;
        competition: {
            code: string;
            id: number;
            name: string;
        };
        homeTeam: {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        };
        awayTeam: {
            id: number;
            name: string;
            shortName: string;
            tla: string;
        };
        score: {
            fullTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            halfTime: {
                home?: number | null | undefined;
                away?: number | null | undefined;
            };
            winner?: string | null | undefined;
            duration?: string | undefined;
        };
        matchday?: number | null | undefined;
        stage?: string | undefined;
        minute?: number | null | undefined;
        injuryTime?: number | null | undefined;
    }[];
}>;
//# sourceMappingURL=api.d.ts.map