/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export interface CompetitionRef {
    id: number;
    name: string;
    code: string;
}
//# sourceMappingURL=competitionRef.d.ts.map