/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export type GetMatchH2HParams = {
    limit?: number;
};
//# sourceMappingURL=getMatchH2HParams.d.ts.map