/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export type GetScoresParams = {
    /**
     * Date in YYYY-MM-DD format (defaults to today)
     */
    date?: string;
};
//# sourceMappingURL=getScoresParams.d.ts.map