/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export type GetStandingsParams = {
    /**
     * League code (e.g. PL, BL1, PD)
     */
    league: string;
};
//# sourceMappingURL=getStandingsParams.d.ts.map