/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export interface GoalEvent {
    minute: number;
    /** @nullable */
    injuryTime?: number | null;
    team: string;
    scorer: string;
    /** @nullable */
    assist?: string | null;
    type?: string;
}
//# sourceMappingURL=goalEvent.d.ts.map