/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export type H2HResultAggregatesAwayTeam = {
    id?: number;
    name?: string;
    wins?: number;
    draws?: number;
    losses?: number;
};
//# sourceMappingURL=h2HResultAggregatesAwayTeam.d.ts.map