/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
import type { H2HResultAggregates } from './h2HResultAggregates';
import type { Match } from './match';

export interface H2HResult {
  aggregates: H2HResultAggregates;
  matches: Match[];
}
