/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
import type { H2HResultAggregatesAwayTeam } from './h2HResultAggregatesAwayTeam';
import type { H2HResultAggregatesHomeTeam } from './h2HResultAggregatesHomeTeam';

export type H2HResultAggregates = {
  numberOfMatches?: number;
  totalGoals?: number;
  homeTeam?: H2HResultAggregatesHomeTeam;
  awayTeam?: H2HResultAggregatesAwayTeam;
};
