/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export * from './competitionRef';
export * from './getFixturesParams';
export * from './getMatchH2HParams';
export * from './getScoresParams';
export * from './getStandingsParams';
export * from './getTeamParams';
export * from './getTopScorersParams';
export * from './goalEvent';
export * from './h2HResult';
export * from './h2HResultAggregates';
export * from './h2HResultAggregatesAwayTeam';
export * from './h2HResultAggregatesHomeTeam';
export * from './healthStatus';
export * from './match';
export * from './matchDetail';
export * from './matchDetailRefereesItem';
export * from './newsArticle';
export * from './score';
export * from './scoreDetail';
export * from './scorer';
export * from './scorerPlayer';
export * from './scorerTeam';
export * from './squadMember';
export * from './standing';
export * from './teamDetail';
export * from './teamRef';
//# sourceMappingURL=index.d.ts.map