/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
import type { CompetitionRef } from './competitionRef';
import type { GoalEvent } from './goalEvent';
import type { MatchDetailRefereesItem } from './matchDetailRefereesItem';
import type { Score } from './score';
import type { TeamRef } from './teamRef';
export interface MatchDetail {
    id: number;
    utcDate: string;
    status: string;
    /** @nullable */
    matchday?: number | null;
    stage?: string;
    /** @nullable */
    minute?: number | null;
    /** @nullable */
    injuryTime?: number | null;
    competition: CompetitionRef;
    homeTeam: TeamRef;
    awayTeam: TeamRef;
    score: Score;
    goals?: GoalEvent[];
    referees?: MatchDetailRefereesItem[];
}
//# sourceMappingURL=matchDetail.d.ts.map