/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
import type { ScoreDetail } from './scoreDetail';
export interface Score {
    /** @nullable */
    winner?: string | null;
    duration?: string;
    fullTime: ScoreDetail;
    halfTime: ScoreDetail;
}
//# sourceMappingURL=score.d.ts.map