/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
import type { ScorerPlayer } from './scorerPlayer';
import type { ScorerTeam } from './scorerTeam';
export interface Scorer {
    player: ScorerPlayer;
    team: ScorerTeam;
    goals: number;
    /** @nullable */
    assists?: number | null;
    /** @nullable */
    penalties?: number | null;
}
//# sourceMappingURL=scorer.d.ts.map