/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export interface ScoreDetail {
    /** @nullable */
    home?: number | null;
    /** @nullable */
    away?: number | null;
}
//# sourceMappingURL=scoreDetail.d.ts.map