/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
import type { CompetitionRef } from './competitionRef';
import type { SquadMember } from './squadMember';

export interface TeamDetail {
  id: number;
  name: string;
  shortName: string;
  tla: string;
  crest: string;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  founded?: number | null;
  /** @nullable */
  clubColors?: string | null;
  /** @nullable */
  venue?: string | null;
  runningCompetitions?: CompetitionRef[];
  squad?: SquadMember[];
}
