/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * GoalWire Football API
 * OpenAPI spec version: 0.1.0
 */
export interface TeamRef {
    id: number;
    name: string;
    shortName: string;
    tla: string;
}
//# sourceMappingURL=teamRef.d.ts.map